version: '3.5'

services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: bash -c "while [ true ]; do sleep 10; done"
    container_name: mmexchange
    volumes:
      - .:/mmexchange
      - gems:/gems
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - db

  db:
    container_name: mmexchange-db
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  gems: