default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres


development:
  <<: *default
  database: MMExchange_development


test:
  <<: *default
  database: MMExchange_test
 

production:
  <<: *default
  database: MMExchange
  username: MMAdmin
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>